### ISSUE TITLE
PHP7.2 Error - 0 [] operator not supported for strings

### ISSUE THREAD

**Issue by ialearn** [SFWLtd/plg_user_teamroles#1]
Hi, 
First off thank you for the plugin.
I use Easyprofile to capture user details in Joomla, Easyprofile automatically adds a tab for "Team Roles" 
The problem I am having is that if I try to update the site to PHP7.2 it stops working.
While PHP7.2 is active if I try to edit any profile linked to the "Team Leader" group I receive an error message  "0 [] operator not supported for strings"
Any advice will be great.

**Comment by ialearn** [comment]
Hi
I managed to fix the error.
plg_user_teamroles/field/team.php  Line 56
`$teamUsersHTML = [];`

**Comment by Spudley** [comment]
Hi @ialearn.

Thanks for the bug report and for finding the fix. Apologies I didn't reply sooner; I've not been around for the week. I've now fixed the bug as per your comment above.

That was a fairly careless error of mine, so thank you for spotting it.
