### ISSUE TITLE
New PHP 7.2 Error Too few arguments to function 

### ISSUE THREAD

**Issue by ialearn** [SFWLtd/plg_user_teamroles#2]
Hi 
I managed to figure out the one error but now there is a new one.
When I change a user's user group thus moving it from one team to another or when I add a user to a second team I get the following error
Error 0 Too few arguments to function TeamRolesUserInfo::__construct(), 1 passed in MyDomainPath/plugins/user/teamroles/TeamRolesUpdater.php on line 114 and at least 3 expected

It seems to still add or remove the individual to or from the team, just with an error

**Comment by ialearn** [comment]
Hi @Spudley 
Any Feedback on this ?

**Comment by ialearn** [comment]
Hi @SFWChrisSmith 
Any Feedback on this ?

**Comment by Spudley** [comment]
Hi.

I have made a commit to the code which should fix the issue for you. Please check it.

Apologies for the delay. I've not had an opportunity to look at it until now.

Analysis:
The error occurred when updating the team leader role in Moodle (via Joomdle). The team details were updated correctly in Joomla but the leadership role was not updated to reflect it in Moodle.
